version: '3.8'
services:
  strapi:
    build:
      dockerfile: dockerfile
      context: .
    environment:
      - DATABASE_URL=postgres://sample-user:sample-pass@db-strapi:5432/sample-db
      - NODE_ENV=local
      - STRAPI_ADMIN_PREVIEW_KEY=abcd1234
      - STRAPI_ADMIN_PREVIEW_HOST_URL=http://localhost:3000
    volumes:
      - ./src:/home/node/app/src
      - ./config:/home/node/app/config
      - ./public:/home/node/app/public
      - ./.env:/home/node/app/.env
      - ./favicon.ico:/home/node/app/favicon.ico
    ports:
      - '1337:1337'
    depends_on:
      - db-strapi