version: '3.8'
services:
  strapi:
    build:
      dockerfile: dockerfile
      context: .
    environment:
      - DATABASE_URL=postgres://sample-user:sample-pass@db-strapi:5432/sample-db
      - NODE_ENV=local
      - STRAPI_ADMIN_PREVIEW_KEY=abcd1234
      - STRAPI_ADMIN_PREVIEW_HOST_URL=http://localhost:3000
    volumes:
      - .:/home/node/app
      # - strapi_build:/home/node/app/build
      # CLEAR VOLUME IF A NEW PACKAGE GOT INSTALLED
      - strapi_module:/home/node/app/node_modules
    ports:
      - '1337:1337'
    depends_on:
      - db-strapi

volumes:
  strapi_module:
  # strapi_build: