# fly.toml file generated for sungryeol-portfolio-db on 2022-06-29T18:06:29+09:00

app = "sungryeol-portfolio-db"
kill_signal = "SIGTERM"
kill_timeout = 300
processes = []
# services = []

[checks]
  [checks.pg]
    grace_period = "30s"
    headers = []
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    port = 5500
    protocol = "http"
    restart_limit = 0
    timeout = "10s"
    tls_skip_verify = false
    type = "http"
  [checks.role]
    grace_period = "30s"
    headers = []
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    port = 5500
    protocol = "http"
    restart_limit = 0
    timeout = "10s"
    tls_skip_verify = false
    type = "http"
  [checks.vm]
    grace_period = "1s"
    headers = []
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    protocol = "http"
    restart_limit = 0
    timeout = "10s"
    tls_skip_verify = false
    type = "http"

[env]
  PRIMARY_REGION = "nrt"

[experimental]
  allowed_public_ports = []
  auto_rollback = false
  enable_consul = true
  private_network = true

[metrics]
  path = "/metrics"
  port = 9187

# https://fly.io/docs/getting-started/multi-region-databases/
# exposing db service via ips

[[mounts]]
  destination = "/data"
  encrypted = false
  source = "pg_data"

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"

# Example of opening port 443 for secure connections
[[services.ports]]
  handlers = ["tls"]
  port = 443

# For insecure connections. 
# [[services.ports]]
#  handlers = []
#  port = 10000